version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: board_db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: board_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
