services:
  db:
    image: mysql:latest
    container_name: board_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: board
      MYSQL_USER: boarduser
      MYSQL_PASSWORD: boardpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: board_app
    ports:
      - "8080:8080"
    environment:
      DB_DSN: "boarduser:boardpass@tcp(db:3306)/board?charset=utf8mb4&parseTime=True&loc=Local"
      JWT_SECRET: "my_jwt_secret"
    depends_on:
      - db
